### ISSUE TITLE
how to port svelte-bun to v8go?

### ISSUE THREAD

**Issue by diyism** [terrywh/svelte-bun#2]
Hi, @terrywh , this project is very impressive, it seems that the svelte file can be built without time.

Do you have any suggest about how to port svelte-bun to v8go(https://github.com/rogchap/v8go)?

I'm wondering the v8go performance compared with the bun.

**Comment by terrywh** [comment]
the entire dependencies contains a lot of js module(code), i'm not sure that's possible.  i think you can try to run the code, and see what's missing or not work, and find the corresponding workaroud. 

Maybe implement the module loader for starters?

**Comment by diyism** [comment]
Thanks, you're right, v8go can't run the built-in api in nodejs:
after I packaged the whole svelte-bun project with:
`./node_modules/.bin/esbuild ./sbin/server.js --bundle --outfile=out.js --format=esm --platform=node`
then run it with test.go:
```
package main

import (
	"fmt"
	"io/ioutil"

	v8 "rogchap.com/v8go"
)

func main() {
	js, _ := ioutil.ReadFile("./out.js")
	ctx:= v8.NewContext()
	val, err := ctx.RunScript(string(js), "main.js")
	if err != nil {
		fmt.Printf("failed to run JavaScript file: %v\n", err)
		return
	}

	fmt.Println(val)
}
```

it shows error:
`failed to run JavaScript file: SyntaxError: Cannot use import statement outside a module`

I guess the corresponding lines are:
```
import { stat as asyncStat } from "fs/promises";
import { extname, join as join2 } from "path";
import { resolve as resolve2 } from "path";
```

Maybe an experienced guy can work around it, but I can't.
